# Generated by Django 3.2.9 on 2021-11-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('id', models.UUIDField(default='7e18bcb66f944c12959e22a83aab07ac', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
