# Generated by Django 3.2.9 on 2021-11-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211123_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='2defb4daf45941698b6bc582a77c69f4', editable=False, primary_key=True, serialize=False),
        ),
    ]
