# Generated by Django 3.2.9 on 2021-11-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.UUIDField(default='24898799f81f4de0a16499f716d3fef4', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fronttire',
            name='id',
            field=models.UUIDField(default='b24259e6d0414ec1a7bbf4bf6d89f1d6', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fronttire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reartire',
            name='id',
            field=models.UUIDField(default='f0a319043ab74fd9b4fcc5a4175f408d', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reartire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='car',
            table='cars',
        ),
    ]
