# Generated by Django 3.2.9 on 2021-11-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211123_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.UUIDField(default='8230d03518144bc3939f62f5fb423581', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fronttire',
            name='id',
            field=models.UUIDField(default='e6a32197f4e749f8849a1336c34d8d0d', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reartire',
            name='id',
            field=models.UUIDField(default='2e5f48f43af046279a086b93d085730b', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='reartire',
            table='rear_tires',
        ),
    ]
