# Generated by Django 3.2.9 on 2021-11-23 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20211123_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.UUIDField(default='2b0373df0ee24d45b7c22cdc3810c38c', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fronttire',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reartire',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
